src/Entity/EDT.php
<?php

namespace App\Entity;

use App\Repository\EDTRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EDTRepository::class)]
class EDT
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Sejour $id_sejour = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $id_medecin = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getIdSejour(): ?Sejour
    {
        return $this->id_sejour;
    }

    public function setIdSejour(?Sejour $id_sejour): static
    {
        $this->id_sejour = $id_sejour;

        return $this;
    }

    public function getIdMedecin(): ?Utilisateur
    {
        return $this->id_medecin;
    }

    public function setIdMedecin(?Utilisateur $id_medecin): static
    {
        $this->id_medecin = $id_medecin;

        return $this;
    }
}

src/Form/EDTType.php
<?php

namespace App\Form;

use App\Entity\EDT;
use App\Entity\Sejour;
use App\Entity\Utilisateur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


use Symfony\Component\Form\Extension\Core\Type\DateType;

use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormInterface;

use App\Entity\Specialite;


class EDTType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
//        var_dump('EDT !');
        $builder
            ->add('date', DateType::class, [
                'attr' => ['readonly' => true],
            ])
            ->add(
                'id_sejour', EntityType::class, [
                    'class' => Sejour::class,
                    'choice_label' => 'id',
                    'attr' => ['class' => 'hidden-field', 'readonly' => true],
                    'label' => false,
                ]
            )
            ->add(
                'id_medecin', EntityType::class, [
                    'class' => Utilisateur::class,
                    'choice_label' => function(Utilisateur $utilisateur) {
                        if($utilisateur->getIdType()->getLabel() == 'Médecin') {
                            return 'Dr. ' . $utilisateur->getPrenom() . ' ' . $utilisateur->getNom();
                        }    
                    },
//                    'choice_filter' => ChoiceList::filter(
//                      $this,
//                      function($test) use ($specialite) {
//                            
//                        if($test instanceof Utilisateur) {
//                            return $test->getIdType()->getLabel() == 'Médecin' && $test->getIdSpecialite() == $specialite;
//                        }
//                        return false;
//                      },
//                      ['medecin']
//                    ),
            ])
        ;
                    
                    
        $formModifier = function (FormInterface $form, Specialite $specialite): void {
            $form->add('id_medecin', EntityType::class, [
                'class' => Utilisateur::class,
//                'placeholder' => '',
                'required' => true,
                'choice_filter' => ChoiceList::filter(
                      $this,
                      function($test) use ($specialite) {
                            
                        if($test instanceof Utilisateur) {
                            return $test->getIdType()->getLabel() == 'Médecin' && $test->getIdSpecialite() == $specialite;
                        }
                        return false;
                      },
                      ['medecin']
                    ),
                    'choice_label' => function(Utilisateur $utilisateur) {
                        if($utilisateur->getIdType()->getLabel() == 'Médecin') {
                            return 'Dr. ' . $utilisateur->getPrenom() . ' ' . $utilisateur->getNom();
                        }
//                        return 'Dr. ' . $utilisateur.getPrenom() . ' ' . $utilisateur->getNom();
                    },
            ]);
        };
        
        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formModifier): void {
                $data = $event->getData();
                if($data) {
                    if(!$data->getIdSejour()->getIdSpecialite()) {
                        $specialite_repository = $this->entityManager->getRepository(Specialite::class);
                        $specialite = $specialite_repository->findAll()[0];
                    } else {
                        $specialite = $data->getIdSejour()->getIdSpecialite();
                    }
                    
                    $formModifier($event->getForm(), $specialite);
                }
            }
        );
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => EDT::class,
        ]);
    }

    public function getBlockPrefix()
    {
        return 'EDTType';
    }
}

src/Controller/EDTController.php
<?php

namespace App\Controller;

use App\Entity\EDT;
use App\Form\EDTType;
use App\Form\CollectionEDTType;
use App\Repository\EDTRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use App\Entity\Sejour;
use App\Entity\CollectionEDT;

use Doctrine\Common\Collections\ArrayCollection;

#[Route('/e/d/t')]
class EDTController extends AbstractController
{
    
    #[Route('/prepare/{id}', name: 'edtPrepare', methods: ['GET', 'POST'])]
    public function prepare(Request $request, Sejour $sejour, EntityManagerInterface $entityManager): Response
    {
        
        $date_range = new \DatePeriod($sejour->getDateDebut(), new \DateInterval('P1D'), $sejour->getDateFin());

        $edts = new CollectionEDT();
        foreach ($date_range as $date) {
            $edt = new EDT();
            $edt->setDate($date);
            $edt->setIdMedecin($sejour->getIdMedecin());
            $edt->setIdSejour($sejour);
            $edts->getCollection()->add($edt);
        }
        
        $edt = new EDT();
        $edt->setIdMedecin($sejour->getIdMedecin());
        $edt->setIdSejour($sejour);
        
        $form = $this->createForm(CollectionEDTType::class, $edts);
        $form->handleRequest($request);

        
            $errors = array();
        if ($form->isSubmitted() && $form->isValid()) {
            
            
            $collection = $form->getData();
            $datas = $collection->getCollection();
            
            $edtRepository = $entityManager->getRepository(EDT::class);
            
            foreach($datas as $data) {
                $existing_edts = $edtRepository->findAllByDate($data->getDate(), $data->getIdMedecin());
                if(count($existing_edts) > 5) {
                    array_push($errors,$data->getDate()->format('d-m-Y') . ' : Un médecin ne peut pas avoir plus de 5 patients par jour');
                }
            }
            
            
            
            if(!$errors) {
              foreach($datas as $data) {
                    $entityManager->persist($data);
                    $entityManager->flush();
                }
                
                return $this->redirectToRoute('adminDashboard', ['id' => $sejour->getIdMedecin()->getId()], Response::HTTP_SEE_OTHER);
            }    
        }
        
        return $this->render('edt/prepare.html.twig', [
            'errors' => $errors,
            'form' => $form,
        ]);
    }
    
    #[Route('/', name: 'app_e_d_t_index', methods: ['GET'])]
    public function index(EDTRepository $eDTRepository): Response
    {
        return $this->render('edt/index.html.twig', [
            'e_d_ts' => $eDTRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_e_d_t_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $eDT = new EDT();
        $form = $this->createForm(EDTType::class, $eDT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($eDT);
            $entityManager->flush();

            return $this->redirectToRoute('app_e_d_t_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('edt/new.html.twig', [
            'e_d_t' => $eDT,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_e_d_t_show', methods: ['GET'])]
    public function show(EDT $eDT): Response
    {
        return $this->render('edt/show.html.twig', [
            'e_d_t' => $eDT,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_e_d_t_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, EDT $eDT, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EDTType::class, $eDT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_e_d_t_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('edt/edit.html.twig', [
            'e_d_t' => $eDT,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_e_d_t_delete', methods: ['POST'])]
    public function delete(Request $request, EDT $eDT, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$eDT->getId(), $request->request->get('_token'))) {
            $entityManager->remove($eDT);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_e_d_t_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/edt/_delete_form.html.twig
<form method="post" action="{{ path('app_e_d_t_delete', {'id': e_d_t.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ e_d_t.id) }}">
    <button class="btn">Delete</button>
</form>

templates/edt/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/edt/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit EDT{% endblock %}

{% block content %}
    <h1>Edition EDT</h1>

    {{ include('edt/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('adminIndex') }}">Retour au Dashboard</a>

{#    {{ include('edt/_delete_form.html.twig') }}#}
{% endblock %}

templates/edt/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}EDT index{% endblock %}

{% block body %}
    <h1>EDT index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for e_d_t in e_d_ts %}
            <tr>
                <td>{{ e_d_t.id }}</td>
                <td>{{ e_d_t.date ? e_d_t.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_e_d_t_show', {'id': e_d_t.id}) }}">show</a>
                    <a href="{{ path('app_e_d_t_edit', {'id': e_d_t.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_e_d_t_new') }}">Create new</a>
{% endblock %}

templates/edt/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EDT{% endblock %}

{% block body %}
    <h1>Create new EDT</h1>

    {{ include('edt/_form.html.twig') }}

    <a href="{{ path('app_e_d_t_index') }}">back to list</a>
{% endblock %}

templates/edt/prepare.html.twig
{% extends 'base.html.twig' %}

{% block title %}New EDT{% endblock %}

{% block content %}
    <h1>Préparer le séjour du patient</h1>
 
    {% for error in errors %}
        {{ error }}
    {% endfor %}
    
{{ form_start(form) }}   
<table>
<tr><th>Date</th><th>Medecin</th></tr>
    {% for edt in form.collection %}
    <tr>
        <td>{{ form_widget(edt.date) }}{{ form_widget(edt.id_sejour) }}</td>
        <td>{{ form_widget(edt.id_medecin) }}</td>
    {% endfor %}
    {{ form_rest(form) }}
</table>
    <button type="submit">Enregistrer</button>
{{ form_end(form) }}
    <a href="{{ path('app_e_d_t_index') }}">back to list</a>
{% endblock %}

templates/edt/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}EDT{% endblock %}

{% block content %}
    <h1>EDT</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Date</th>
                <td>{{ e_d_t.date ? e_d_t.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Medecin</th>
                <td>Dr. {{ e_d_t.idMedecin.prenom }} {{ e_d_t.idMedecin.nom }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('adminIndex') }}">Retour</a>

    <a href="{{ path('app_e_d_t_edit', {'id': e_d_t.id}) }}">Editer</a>

{#    {{ include('edt/_delete_form.html.twig') }}#}
{% endblock %}